# ndarray
## 1. ndarray 的特性
### 多维性

In [2]:
import numpy as np

In [3]:
arr = np.array(5) # 创建一个 0 维 ndarray 数组
print(arr)
print('arr的维度: ', arr.ndim) # 数组的维度 number of dimensions

5
arr的维度:  0


In [6]:
arr = np.array([1, 2, 3]) # 创建一个 1 维的 ndarray 数组
print(arr)
print('arr的维度: ', arr.ndim) # 数组维度 number of dimensions

[1 2 3]
arr的维度:  1


In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6]]) # 创建一个 2 维的 ndarray 数组
print(arr)
print('arr的维度: ', arr.ndim) # 数组维度 number of dimensions

[[1 2 3]
 [4 5 6]]
arr的维度:  2


### 同质性

In [8]:
arr = np.array([1, 'hello']) # 数据类型不同，会被强制转换为相同的数据类型
print(arr)

['1' 'hello']


In [9]:
arr = np.array([1, 2.5]) # 数据类型不同，会被强制转换为相同的数据类型
print(arr)

[1.  2.5]


## 2. ndarray 的属性

In [28]:
arr = np.array(1)
print(arr)
print('数组的形状\n', arr.shape)
print('数组的维度', arr.ndim)
print('元素的个数', arr.size)
print('元素的数据类型', arr.dtype)
print('元素的转置\n', arr.T)

1
数组的形状
 ()
数组的维度 0
元素的个数 1
元素的数据类型 int64
元素的转置
 1


In [29]:
arr = np.array([1, 2, 3])
print(arr)
print('数组的形状\n', arr.shape)
print('数组的维度', arr.ndim)
print('元素的个数', arr.size)
print('元素的数据类型', arr.dtype)
print('元素的转置\n', arr.T)

[1 2 3]
数组的形状
 (3,)
数组的维度 1
元素的个数 3
元素的数据类型 int64
元素的转置
 [1 2 3]


In [30]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print('数组的形状\n', arr.shape)
print('数组的维度', arr.ndim)
print('元素的个数', arr.size)
print('元素的数据类型', arr.dtype)
print('元素的转置\n', arr.T)

[[1 2 3]
 [4 5 6]]
数组的形状
 (2, 3)
数组的维度 2
元素的个数 6
元素的数据类型 int64
元素的转置
 [[1 4]
 [2 5]
 [3 6]]


## 3. ndarray 的创建