# ndarray
## 1. ndarray 的特性
### 多维性

In [1]:
import numpy as np

In [2]:
arr = np.array(5) # 创建一个 0 维 ndarray 数组
print(arr)
print('arr的维度: ', arr.ndim) # 数组的维度 number of dimensions

5
arr的维度:  0


In [3]:
arr = np.array([1, 2, 3]) # 创建一个 1 维的 ndarray 数组
print(arr)
print('arr的维度: ', arr.ndim) # 数组维度 number of dimensions

[1 2 3]
arr的维度:  1


In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6]]) # 创建一个 2 维的 ndarray 数组
print(arr)
print('arr的维度: ', arr.ndim) # 数组维度 number of dimensions

[[1 2 3]
 [4 5 6]]
arr的维度:  2


### 同质性

In [5]:
arr = np.array([1, 'hello']) # 数据类型不同，会被强制转换为相同的数据类型
print(arr)

['1' 'hello']


In [6]:
arr = np.array([1, 2.5]) # 数据类型不同，会被强制转换为相同的数据类型
print(arr)

[1.  2.5]


## 2. ndarray 的属性

In [7]:
arr = np.array(1)
print(arr)
print('数组的形状\n', arr.shape)
print('数组的维度', arr.ndim)
print('元素的个数', arr.size)
print('元素的数据类型', arr.dtype)
print('元素的转置\n', arr.T)

1
数组的形状
 ()
数组的维度 0
元素的个数 1
元素的数据类型 int64
元素的转置
 1


In [8]:
arr = np.array([1, 2, 3])
print(arr)
print('数组的形状\n', arr.shape)
print('数组的维度', arr.ndim)
print('元素的个数', arr.size)
print('元素的数据类型', arr.dtype)
print('元素的转置\n', arr.T)

[1 2 3]
数组的形状
 (3,)
数组的维度 1
元素的个数 3
元素的数据类型 int64
元素的转置
 [1 2 3]


In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print('数组的形状\n', arr.shape)
print('数组的维度', arr.ndim)
print('元素的个数', arr.size)
print('元素的数据类型', arr.dtype)
print('元素的转置\n', arr.T)

[[1 2 3]
 [4 5 6]]
数组的形状
 (2, 3)
数组的维度 2
元素的个数 6
元素的数据类型 int64
元素的转置
 [[1 4]
 [2 5]
 [3 6]]


## 3. ndarray 的创建

In [10]:
# 基础创建方法
list1 = [4, 5, 6]
arr = np.array(list1, dtype=np.float64)
print(arr.ndim)
print(arr)

1
[4. 5. 6.]


In [11]:
# copy
arr1 = np.copy(arr) # 元素和原始数组相同，但已经是不同的数组了
print(arr1)
arr1[0] = 8
print(arr1)
print(arr)

[4. 5. 6.]
[8. 5. 6.]
[4. 5. 6.]


In [12]:
# 预定义形状
# 全 0 全 1 未初始化 固定值
# 全 0
arr = np.zeros((2, 3), dtype=int)
print(arr)
print(arr.dtype)

[[0 0 0]
 [0 0 0]]
int64


In [13]:
arr = np.zeros((3, ), dtype=int)
print(arr)
print(arr.dtype)

[0 0 0]
int64


In [14]:
# 全 1
arr = np.ones((5, 8), dtype=int)
print(arr)

[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


In [15]:
# 未初始化
arr = np.empty((4, 5))
print(arr)


[[0.  0.  0.3 1.  0. ]
 [0.  1.  1.  1.  1. ]
 [1.  1.  1.  0.  0. ]
 [1.  0.5 0.  0.  1. ]]


In [16]:
# 固定值
arr = np.full((4,5), 315)
print(arr)

[[315 315 315 315 315]
 [315 315 315 315 315]
 [315 315 315 315 315]
 [315 315 315 315 315]]


In [17]:
arr1 = np.zeros_like(arr) # 形状一样
print(arr1)
arr1 = np.empty_like(arr) # 形状一样
print(arr1)
arr1 = np.ones_like(arr) # 形状一样
print(arr1)
arr1 = np.full_like(arr, 515) # 形状一样
print(arr1)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[25895968444448860 18296268626985028 31244147623002222 26740539405893742
  32370129135075429]
 [33214519704879196 27303502243692659 27303480769183860 34058936044814446
  25896191785500787]
 [25896118771056748 28429470870863987 27866439313522733 28429415035764843
  31525665549058163]
 [31244220637315180 29555332123197551 30681167605989492 32651574046883952
  12947848935243827]]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[515 515 515 515 515]
 [515 515 515 515 515]
 [515 515 515 515 515]
 [515 515 515 515 515]]


In [18]:
# 等差数列 例如：2, 4, 6, 8
arr = np.arange(1, 51, 1) # start, end, step
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


In [19]:
# 等间隔数列
arr = np.linspace(0, 100, 5)
print(arr)

[  0.  25.  50.  75. 100.]


In [20]:
arr = np.linspace(0, 100, 5, dtype=int)
print(arr)
arr = np.arange(0, 101, 25)
print(arr)

[  0  25  50  75 100]
[  0  25  50  75 100]


In [21]:
# 对数间隔数列
arr = np.logspace(0, 4, 3, base=2)
print(arr)

[ 1.  4. 16.]


In [22]:
arr = np.linspace(0, 4, 3)
print(arr)

[0. 2. 4.]


In [23]:
arr = np.logspace(0, 4, 3)
print(arr)

[1.e+00 1.e+02 1.e+04]


In [24]:
# 特殊矩阵构造
# 单位矩阵：主对角线上的数字为 1 ，其他位置为 0
arr = np.eye(3, 4, dtype=int)
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [25]:
# 对角矩阵：主对角线上是非 0 的数，其他位置为 0
arr = np.diag([1, 2, 3, 4, 5]) # 参数是主对角线上要填充的数字
print(arr)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [26]:
# 随机数组的生成
# 生成 0 - 1 之间的浮点数(均匀分布)
arr = np.random.rand(2, 3)
print(arr)

[[0.57583997 0.35679763 0.97980229]
 [0.81164257 0.80526364 0.3571538 ]]


In [27]:
# 生成指定范围区间的随机浮点数（均匀分布）
arr = np.random.uniform(3, 6, (2, 3))
print(arr)

[[5.19307639 3.04446998 3.65712526]
 [3.37493339 4.67949562 4.23684699]]


In [28]:
# 生成指定范围区间的随机整数（均匀分布）
arr = np.random.randint(3, 30, (2, 3))
print(arr)

[[14  3 16]
 [13 28 29]]


In [29]:
# 生成随机数列（正太分布）
# 两边的概率小，中间的概率大
arr = np.random.randn(2, 3)
print(arr)

[[-2.58488794 -1.59377215 -2.3136016 ]
 [-1.43311051 -0.55161308  0.13025219]]


In [30]:
# 设置随机种子
np.random.seed(42)
arr = np.random.randint(1, 10, (2, 5))
print(arr)

[[7 4 8 5 7]
 [3 7 8 5 4]]


## 4. ndarray 的数据类型
| 类型   | 名称       |
|------|----------|
| 布尔类型 | bool     |
| 整型   | int uint |
| 浮点型  | float    |
| 复数   | complex  |

In [31]:
arr = np.array([1, 0, 128, 0], dtype=int)
print(arr)

[  1   0 128   0]


## 5. 索引与切片

In [32]:
# 一维数组的索引与切片
arr = np.random.randint(1, 100, 20)
print(arr)

[24  3 22 53  2 88 30 38  2 64 60 21 33 76 58 22 89 49 91 59]


In [33]:
print(arr[0])
print(arr[:]) # 获取全部数据
print(arr[2:5]) # start:end+1 左闭右开
print(arr[slice(2, 15, 3)]) # start, end, step
print(arr[(arr > 10) & (arr < 70)]) # 布尔索引

24
[24  3 22 53  2 88 30 38  2 64 60 21 33 76 58 22 89 49 91 59]
[22 53  2]
[22 88  2 21 58]
[24 22 53 30 38 64 60 21 33 58 22 49 59]


In [34]:
# 二维数组的索引与切片
arr = np.random.randint(1, 100, (4, 8))
print(arr)

[[42 92 60 80 15 62 62 47]
 [62 51 55 64  3 51  7 21]
 [73 39 18  4 89 60 14  9]
 [90 53  2 84 92 60 71 44]]


In [35]:
print(arr[1, 3]) # 索引
print(arr[1, 2:5])
print(arr[arr > 50]) # 返回结果为一维数组
print(arr[2][arr[2] > 50]) # 第三行大于50
print(arr[:, 2][arr[:, 2] > 50]) # 第三列大于50

64
[55 64  3]
[92 60 80 62 62 62 51 55 64 51 73 89 60 90 53 84 92 60 71]
[73 89 60]
[60 55]


## 6. ndarray 的运算

In [36]:
# 算数运算
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [37]:
c = [1, 2, 3]
d = [4, 5, 6]
print(c + d) # 拼接
for i in range(len(c)):
    d[i] += c[i]
print(d)

[1, 2, 3, 4, 5, 6]
[5, 7, 9]


In [38]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[4, 5, 6], [7, 8, 9], [1, 2, 3]])
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** b)

[[ 5  7  9]
 [11 13 15]
 [ 8 10 12]]
[[-3 -3 -3]
 [-3 -3 -3]
 [ 6  6  6]]
[[ 4 10 18]
 [28 40 54]
 [ 7 16 27]]
[[0.25       0.4        0.5       ]
 [0.57142857 0.625      0.66666667]
 [7.         4.         3.        ]]
[[       1       32      729]
 [   16384   390625 10077696]
 [       7       64      729]]


In [39]:
# 数组与标量之间的算术运算
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[4, 5, 6], [7, 8, 9], [1, 2, 3]])
print(a + 3)
print(a * 3)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [40]:
# 广播机制: 1. 获取形状 2. 是否可以广播
# 同一维度：相同、为1
a = np.array([1, 2, 3]) # 1 * 3
b = np.array([[4], [5], [6]]) # 3 * 1
print(a + b)
print(b - a)
'''
a
1 2 3
1 2 3
1 2 3

b
4 4 4
5 5 4
6 6 6
'''


[[5 6 7]
 [6 7 8]
 [7 8 9]]
[[3 2 1]
 [4 3 2]
 [5 4 3]]


'\na\n1 2 3\n1 2 3\n1 2 3\n\nb\n4 4 4\n5 5 4\n6 6 6\n'

In [41]:
# 不可广播的示例
a = np.array([1, 2, 3]) # 1 * 3
b = np.array([4, 5]) # 1 * 2
# print(a - b)

In [42]:
# 矩阵运算
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[4, 5, 6], [7, 8, 9], [1, 2, 3]])
print(a * b) # 算术乘法
print(a @ b) # 矩阵乘法

[[ 4 10 18]
 [28 40 54]
 [ 7 16 27]]
[[ 21  27  33]
 [ 57  72  87]
 [ 93 117 141]]


# numpy 中的常用函数
## 1. 基本的数学函数

In [43]:
# 计算平方根
print(np.sqrt(9))
print(np.sqrt([1, 4, 9]))
arr = np.array([1, 25, 81])
print(np.sqrt(arr))

3.0
[1. 2. 3.]
[1. 5. 9.]


In [44]:
# 计算指数 e^x
print(np.exp(1)) # 默认以 e 为底

2.718281828459045


In [45]:
# 计算自然对数 lnx
print(np.log(2.71))

0.9969486348916096


In [46]:
# 计算正弦值、余弦值
print(np.sin(np.pi/2))
print(np.cos(np.pi))

1.0
-1.0


In [47]:
# 计算绝对值
arr = np.array([-1, 1, 2, -3])
print(np.abs(arr))

[1 1 2 3]


In [48]:
# 计算 a 的 b 次幂
print(np.power(arr, 3))

[ -1   1   8 -27]


In [49]:
# 四舍五入 5后有数字直接进位，后无数字偶舍奇入
print(np.round([3.2, 4.5, 8.1, 9.6]))

[ 3.  4.  8. 10.]


In [50]:
# 向下取整、向上取整
arr = np.array([1.6, 25.1, 81.7])
print(np.ceil(arr))
print(np.floor(arr))

[ 2. 26. 82.]
[ 1. 25. 81.]


In [51]:
# 检测缺失值
np.isnan([1, 2, np.nan, 3])
print(np.isnan([1, 2, np.nan, 3]))

[False False  True False]


## 2. 统计函数

求和 计算平均值 中位数 标准差 方差
查找最大值 最小值
计算分位数 累积和 累积积

In [52]:
arr = np.random.randint(1, 20, 8)
print(arr)

[ 8 15  3 14 17  4 18  8]


In [53]:
# 求和
print(np.sum(arr))
print(np.sum([1, 2, 3]))

87
6


In [54]:
# 计算平均值
print(np.mean(arr))
print(np.mean([1, 2, 3]))
print(np.mean([1, 1, 1, 1, 1, 1, 1, 1, 100]))

10.875
2.0
12.0


In [55]:
# 计算中位数 奇数：排序后中间的数，偶数：排序后中间两个数的平均值
print(np.median([1, 2, 4]))
print(np.median([1, 2, 4, 8]))
print(np.median([1, 1, 1, 1, 1, 1, 1, 1, 100]))
print(np.median(arr))

2.0
3.0
1.0
11.0


In [58]:
# 计算标准差 方差
# [(1 - 2) ^ 2 + (2 - 2) ^ 2 + (3 - 2) ^ 2] / 3 = 2/3
# (2/3) ^ (1/2)
print(np.var([1, 2, 3]))
print(np.std([1, 2, 3]))
print(np.var(arr))
print(np.std(arr))
arr1 = np.array([1, 0, 3, 0, 0, 0, 4, 3])
arr2 = np.array([1, 2, 1, 2, 1, 1, 1, 2])
print(np.mean(arr1))
print(np.mean(arr2))
print(np.var(arr1))
print(np.var(arr2))

0.6666666666666666
0.816496580927726
30.109375
5.4872010169119925
1.375
1.375
2.484375
0.234375


In [61]:
# 取最大值、最小值
print(arr)
print(np.max(arr), np.argmax(arr))
print(np.min(arr), np.argmin(arr))

[ 8 15  3 14 17  4 18  8]
18 6
3 2


In [72]:
# 分位数
# 中位数
# -------------
# 1     2     3
# 1   2   3   4
print(np.median([1, 2, 3]))
print(np.median([1, 2, 3, 4]))
np.random.seed(0)
arr = np.random.randint(0, 100, 4)
print(arr)
# --------------
# 44  47  64  67
# (47 + 64) /2 = 55.5
print(np.median(arr))
# 0.25 * 3 = 0.75
# (47 - 44) * 0.75 + 44 = 46.25
print(np.percentile(arr, 25))

2.0
2.5
[44 47 64 67]
55.5
46.25


In [75]:
# 累计和 累积积
arr = np.array([1, 2, 3])
print(np.sum(arr))
print(np.cumsum(arr))
print(np.cumprod(arr))

6
[1 3 6]
[1 2 6]


## 3. 比较函数
大于 小于 等于
逻辑与 或 非
检查数组中是否有一个True 是否全为 True
自定义条件

In [81]:
# 是否大于
print(np.greater([3, 4, 5, 6, 7, 8], 4))
# 是否小于
print(np.less([3, 4, 5, 6, 7, 8], 4))
# 是否等于
print(np.equal([3, 4, 5, 6, 7, 8], 4))
print(np.equal([3, 4, 5], [4, 4, 4]))

[False False  True  True  True  True]
[ True False False False False False]
[False  True False False False False]
[False  True False]


In [85]:
# 逻辑与
print(np.logical_and([1, 0], [1, 1]))
# 逻辑非
print(np.logical_not([1, 0]))
# 逻辑或
print(np.logical_or([1, 0], [1, 1]))

[ True False]
[False  True]
[ True  True]


In [86]:
# 检查是否有至少一个元素为True
print(np.any([0, 0, 0, 0]))
# 检查是否全部元素为True
print(np.all([1, 1, 1, 0]))

False
False


In [88]:
# 自定义条件
# np.where(条件,符合条件取,不符合条件取)
arr = np.array([1, 2, 3, 4, 5])
print(np.where(arr > 3, arr, 0))
print(np.where(arr < 3, 0, 1))

[0 0 0 4 5]
[0 0 1 1 1]


In [89]:
score = np.random.randint(50, 100, 20)
print(np.where(score >= 60, '及格', '不及格'))

['不及格' '及格' '不及格' '及格' '及格' '及格' '及格' '不及格' '及格' '及格' '及格' '不及格' '及格' '及格'
 '及格' '及格' '及格' '及格' '及格' '及格']


In [90]:
print(np.where(
    score < 60, '不及格', np.where(
        score < 80, '良好', '优秀'
    )
))

['不及格' '优秀' '不及格' '良好' '良好' '优秀' '良好' '不及格' '良好' '良好' '良好' '不及格' '优秀' '优秀'
 '良好' '优秀' '良好' '良好' '优秀' '良好']


In [94]:
# np.select(条件, 返回结果)
print(np.select([score < 60, (score >= 60) & (score < 80), score >= 80 ], ['不及格', '良好', '优秀'], default='未知'))

['不及格' '优秀' '不及格' '良好' '良好' '优秀' '良好' '不及格' '良好' '良好' '良好' '不及格' '优秀' '优秀'
 '良好' '优秀' '良好' '良好' '优秀' '良好']


## 4. 排序函数

In [107]:
np.random.seed(0)
arr = np.random.randint(1, 100, 20)
print(arr)
# arr.sort() # 改变原始数组
# print(arr)
print(np.sort(arr)) # 不改变原始数组，返回排序后的结果
print(np.argsort(arr)) # 获取原数组中每个元素的排序索引
print(arr)

[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]
[10 13 22 37 40 45 47 48 59 65 66 68 68 71 84 88 88 89 89 89]
[ 5 13  7  8 16  0 18  1 14  2 15  3  4 10  6  9 17 11 12 19]
[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]


In [108]:
# 去重函数
print(np.unique(arr)) # 去重同时排序

[10 13 22 37 40 45 47 48 59 65 66 68 71 84 88 89]


In [113]:
# 数组的拼接
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1 + arr2)
print(np.concatenate((arr1, arr2)))


[5 7 9]
[1 2 3 4 5 6]


In [116]:
# 数组的分割
print(np.split(arr, 4))
print(np.split(arr, 5))
print(np.split(arr, [6, 12, 18]))

[array([45, 48, 65, 68, 68], dtype=int32), array([10, 84, 22, 37, 88], dtype=int32), array([71, 89, 89, 13, 59], dtype=int32), array([66, 40, 88, 47, 89], dtype=int32)]
[array([45, 48, 65, 68], dtype=int32), array([68, 10, 84, 22], dtype=int32), array([37, 88, 71, 89], dtype=int32), array([89, 13, 59, 66], dtype=int32), array([40, 88, 47, 89], dtype=int32)]
[array([45, 48, 65, 68, 68, 10], dtype=int32), array([84, 22, 37, 88, 71, 89], dtype=int32), array([89, 13, 59, 66, 40, 88], dtype=int32), array([47, 89], dtype=int32)]


In [118]:
# 调整数组形状
print(np.reshape(arr, [4, 5]))
print(np.reshape(arr, [5, 4]))

[[45 48 65 68 68]
 [10 84 22 37 88]
 [71 89 89 13 59]
 [66 40 88 47 89]]
[[45 48 65 68]
 [68 10 84 22]
 [37 88 71 89]
 [89 13 59 66]
 [40 88 47 89]]
