# Numpy 科学计算练习

In [22]:
import numpy as np

In [ ]:
'''
题目 1 ：温度数据分析
某城市一周的日最高气温（℃）为：[28, 30, 29, 31, 32, 30, 29]
- 计算平均气温、最高气温和最低气温
- 找出气温超过 30℃ 的 天数
'''

In [23]:
temps = np.array([28, 30, 29, 31, 32, 30, 29])
print(temps)
print('平均气温：%.3f' %np.mean(temps))
print('最高气温：', np.max(temps))
print('最低气温：', np.min(temps))
print('气温超过30℃的天数：', temps[temps > 30].size)
print('气温超过30℃的天数：', np.sum(np.where(temps > 30, 1, 0)))
print('气温超过30℃的天数：', np.cumsum(np.where(temps > 30, 1, 0))[-1])
print('气温超过30℃的天数：', np.count_nonzero(temps > 30))

[28 30 29 31 32 30 29]
平均气温：29.857
最高气温： 32
最低气温： 28
气温超过30℃的天数： 2
气温超过30℃的天数： 2
气温超过30℃的天数： 2
气温超过30℃的天数： 2


In [ ]:
'''
题目 2 ：学生成绩统计
某班级某 5 名同学的数学成绩为：[85, 90, 78, 92, 88]
- 计算成绩平均分、中位数、标准差
- 将成绩转换为十分制（满分10分）
'''

In [24]:
score = np.array([85, 90, 78, 92, 88])
print(score)
print(np.sort(score))
print('平均分：', np.mean(score))
print('中位数：', np.median(score))
print('标准差：%.3f' % np.std(score))
print('十分制：', score/10)

[85 90 78 92 88]
[78 85 88 90 92]
平均分： 86.6
中位数： 88.0
标准差：4.883
十分制： [8.5 9.  7.8 9.2 8.8]


In [ ]:
'''
题目 3 ：矩阵运算
给定矩阵 A = [[1, 2], [3, 4]] 和 B = [[5, 6,], [7, 8]]
- 计算 A + B 和 A * B （逐元素乘法）
- 计算 A 和 B 的矩阵乘法（点积）
'''

In [25]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6,], [7, 8]])
print(A + B)
print(A * B)
print(A @ B)
print(np.dot(A, B))

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [ ]:
'''
题目 4 ：随机数据生成
生成一个 (3, 4) 的随机整数数组，取值范围为 [0, 10)
- 计算每行的最大值和每列的最小值
- 将数组中所有的奇数替换为 -1
'''

In [26]:
np.random.seed(0)
arr = np.random.randint(0, 10, (3, 4))
print(arr)
print('每列的最大值：', np.max(arr, axis=0)) # axis=0 代表列，axis=0代表行
print('每行的最小值：', np.min(arr, axis=1))
print(np.where(arr % 2 == 1, -1, arr))
arr[arr % 2 == 1] = -1
print(arr)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
每列的最大值： [7 9 7 6]
每行的最小值： [0 3 2]
[[-1  0 -1 -1]
 [-1 -1 -1 -1]
 [ 2  4 -1  6]]
[[-1  0 -1 -1]
 [-1 -1 -1 -1]
 [ 2  4 -1  6]]


In [ ]:
'''
题目 5 ：数组变形
创建一个 1 到 12 的一维数组，转换为 (3, 4) 的二维数组
- 求每行的和与每列的平均值
- 将数组展平为一维数组
'''

In [27]:
# arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr = np.arange(1, 13)
print(arr)
arr = np.reshape(arr,(3, 4))
print(arr)
print(np.sum(arr,axis=1))
print(np.mean(arr, axis=0))
arr = np.reshape(arr, (12,))
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[10 26 42]
[5. 6. 7. 8.]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
'''
题目 6 ：布尔索引
生成一个 (5, 5) 的随机数组，范围为：[0, 20)
- 找出数组中大于 10 的元素
- 把所有大于 10 的元素替换为 0
'''

In [28]:
np.random.seed(0)
arr = np.random.randint(0, 20, (5, 5))
print(arr)
print(arr[arr > 10])
arr[arr > 10] = 0
print(arr)

[[12 15  0  3  3]
 [ 7  9 19 18  4]
 [ 6 12  1  6  7]
 [14 17  5 13  8]
 [ 9 19 16 19  5]]
[12 15 19 18 12 14 17 13 19 16 19]
[[0 0 0 3 3]
 [7 9 0 0 4]
 [6 0 1 6 7]
 [0 0 5 0 8]
 [9 0 0 0 5]]


In [ ]:
'''
题目 7 : 统计函数的应用
某个公司 6 个月的销售额（万元）[120, 135, 110, 125, 130, 140]
- 计算销售额的总值、均值、方差
- 找出销售额最高的月份和最低的月份
'''

In [29]:
money = np.array([120, 135, 110, 125, 130, 140])
print('销售总额: ', np.sum(money))
print('平均销售额：', np.mean(money))
print('方差：', np.var(money))
print('销售额最高的月份：', np.argmax(money) + 1)
print('销售额最低的月份：', np.argmin(money) + 1)

销售总额:  760
平均销售额： 126.66666666666667
方差： 97.22222222222223
销售额最高的月份： 6
销售额最低的月份： 3


In [ ]:
'''
题目 8：数组拼接
给定 A = [1, 2, 3] 和 B = [4, 5, 6]
- 将 A 和 B 水平拼接为一个新数组
- 将 A 和 B 竖直拼接为一个新数组
'''

In [30]:
A = np.array([1, 2, 3])
B =  np.array([4, 5, 6])
C = np.concatenate((A, B))
print(C)
D = np.reshape(C, (2, 3))
print(D)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [ ]:
'''
题目 9 ：唯一值与排序
给定一个数组 [2, 1, 2, 3, 1, 4, 3]
- 找出数组中的唯一值并排序
- 计算每个唯一值出现的次数
'''

In [31]:
arr = np.array([2, 1, 2, 3, 1, 4, 3])
uni_arr, counts = np.unique(arr, return_counts=True)
print(uni_arr)
print(counts)
res = []
for i in range(len(uni_arr)):
    res.append(arr[arr == uni_arr[i]].size)
print(res)

[1 2 3 4]
[2 2 2 1]
[2, 2, 2, 1]


In [ ]:
'''
题目 10：综合应用
某商店 5 天的销售额（万元）和成本（万元）如下：
销售额：[20, 25, 22, 28, 30]
成本：[15, 18, 16, 22, 20]
- 计算每天的利润（销售额 - 成本）
- 计算利润的平均值和标注差
- 找出利润最高的天数
'''

In [32]:
money = np.array([20, 25, 22, 30, 28])
a = np.array([15, 18, 16, 22, 20])
b = money - a
print('每天的利润：', b)
print('利润的平均值：', np.mean(b))
print('利润的标注差', np.std(b))
print('利润最高的天数：', b[np.max(b) == b].size)

每天的利润： [5 7 6 8 8]
利润的平均值： 6.8
利润的标注差 1.16619037896906
利润最高的天数： 2
