# ndarray
## 1. ndarray 的特性
### 多维性

In [1]:
import numpy as np

In [2]:
arr = np.array(5) # 创建一个 0 维 ndarray 数组
print(arr)
print('arr的维度: ', arr.ndim) # 数组的维度 number of dimensions

5
arr的维度:  0


In [3]:
arr = np.array([1, 2, 3]) # 创建一个 1 维的 ndarray 数组
print(arr)
print('arr的维度: ', arr.ndim) # 数组维度 number of dimensions

[1 2 3]
arr的维度:  1


In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6]]) # 创建一个 2 维的 ndarray 数组
print(arr)
print('arr的维度: ', arr.ndim) # 数组维度 number of dimensions

[[1 2 3]
 [4 5 6]]
arr的维度:  2


### 同质性

In [5]:
arr = np.array([1, 'hello']) # 数据类型不同，会被强制转换为相同的数据类型
print(arr)

['1' 'hello']


In [6]:
arr = np.array([1, 2.5]) # 数据类型不同，会被强制转换为相同的数据类型
print(arr)

[1.  2.5]


## 2. ndarray 的属性

In [7]:
arr = np.array(1)
print(arr)
print('数组的形状\n', arr.shape)
print('数组的维度', arr.ndim)
print('元素的个数', arr.size)
print('元素的数据类型', arr.dtype)
print('元素的转置\n', arr.T)

1
数组的形状
 ()
数组的维度 0
元素的个数 1
元素的数据类型 int64
元素的转置
 1


In [8]:
arr = np.array([1, 2, 3])
print(arr)
print('数组的形状\n', arr.shape)
print('数组的维度', arr.ndim)
print('元素的个数', arr.size)
print('元素的数据类型', arr.dtype)
print('元素的转置\n', arr.T)

[1 2 3]
数组的形状
 (3,)
数组的维度 1
元素的个数 3
元素的数据类型 int64
元素的转置
 [1 2 3]


In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print('数组的形状\n', arr.shape)
print('数组的维度', arr.ndim)
print('元素的个数', arr.size)
print('元素的数据类型', arr.dtype)
print('元素的转置\n', arr.T)

[[1 2 3]
 [4 5 6]]
数组的形状
 (2, 3)
数组的维度 2
元素的个数 6
元素的数据类型 int64
元素的转置
 [[1 4]
 [2 5]
 [3 6]]


## 3. ndarray 的创建

In [18]:
# 基础创建方法
list1 = [4, 5, 6]
arr = np.array(list1, dtype=np.float64)
print(arr.ndim)
print(arr)

1
[4. 5. 6.]


In [19]:
# copy
arr1 = np.copy(arr) # 元素和原始数组相同，但已经是不同的数组了
print(arr1)
arr1[0] = 8
print(arr1)
print(arr)

[4. 5. 6.]
[8. 5. 6.]
[4. 5. 6.]


In [22]:
# 预定义形状
# 全 0 全 1 未初始化 固定值
# 全 0
arr = np.zeros((2, 3), dtype=int)
print(arr)
print(arr.dtype)

[[0 0 0]
 [0 0 0]]
int64


In [26]:
arr = np.zeros((3, ), dtype=int)
print(arr)
print(arr.dtype)

[0 0 0]
int64


In [24]:
# 全 1
arr = np.ones((5, 8), dtype=int)
print(arr)

[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


In [28]:
# 未初始化
arr = np.empty((4, 5))
print(arr)


[[0.  0.  0.3 1.  0. ]
 [0.  1.  1.  1.  1. ]
 [1.  1.  1.  0.  0. ]
 [1.  0.5 0.  0.  1. ]]


In [29]:
# 固定值
arr = np.full((4,5), 315)
print(arr)

[[315 315 315 315 315]
 [315 315 315 315 315]
 [315 315 315 315 315]
 [315 315 315 315 315]]


In [34]:
arr1 = np.zeros_like(arr) # 形状一样
print(arr1)
arr1 = np.empty_like(arr) # 形状一样
print(arr1)
arr1 = np.ones_like(arr) # 形状一样
print(arr1)
arr1 = np.full_like(arr, 515) # 形状一样
print(arr1)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[515 515 515 515 515]
 [515 515 515 515 515]
 [515 515 515 515 515]
 [515 515 515 515 515]]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[515 515 515 515 515]
 [515 515 515 515 515]
 [515 515 515 515 515]
 [515 515 515 515 515]]


In [37]:
# 等差数列 例如：2, 4, 6, 8
arr = np.arange(1, 51, 1) # start, end, step
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


In [40]:
# 等间隔数列
arr = np.linspace(0, 100, 5)
print(arr)

[  0.  25.  50.  75. 100.]


In [42]:
arr = np.linspace(0, 100, 5, dtype=int)
print(arr)
arr = np.arange(0, 101, 25)
print(arr)

[  0  25  50  75 100]
[  0  25  50  75 100]


In [43]:
# 对数间隔数列
arr = np.logspace(0, 4, 3, base=2)
print(arr)

[ 1.  4. 16.]


In [44]:
arr = np.linspace(0, 4, 3)
print(arr)

[0. 2. 4.]


In [45]:
arr = np.logspace(0, 4, 3)
print(arr)

[1.e+00 1.e+02 1.e+04]


In [48]:
# 特殊矩阵构造
# 单位矩阵：主对角线上的数字为 1 ，其他位置为 0
arr = np.eye(3, 4, dtype=int)
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [ ]:
# 对角矩阵：主对角线上是非 0 的数，其他位置为 0

